name: Publish package on npm

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd /home/runner/work/hbuilderx-plugins/hbuilderx-plugins/npm_packages && npm ci
      - run: cd /home/runner/work/hbuilderx-plugins/hbuilderx-plugins/npm_packages && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
